version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
 build: 
  commands:
   - sam build
   - export BUCKET=pipeline-output-bucket1321
   - aws cloudformation package --template-file template.yml --s3-bucket pipeline-output-bucket1321 

artifacts:
 type: zip
 files:
  - template.yml
